<?php

namespace Bricks\SiteBundle\Entity;

use DoctrineExtensions\Taggable\Entity\TagRepository as BaseTagRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends BaseTagRepository
{
}
