# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java:           %java_path%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        lessphp:
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: false

    assets:
        lesses:
            inputs:
                # BricksSiteBundle
                - bundles/brickssite/less/layout.less
                - bundles/brickssite/less/controller-default.less
                - bundles/brickssite/less/controller-brick.less
                - bundles/brickssite/less/syntax-highlight.less
                - bundles/brickssite/less/controller-user_profile.less
                - bundles/brickssite/less/route-exception.less

                - bundles/brickssite/less/*.less
                - bundles/brickswiki/less/*.less
                - bundles/bricksuser/less/*.less
                - bundles/bricksmessage/less/*.less

                # responsive
                - bundles/brickssite/less/responsive.less

            filters: lessphp
        stylesheets:
            inputs:
                - %kernel.root_dir%/../web/assets/bootstrap-3.0.0/dist/css/bootstrap.min.css
                - @lesses
                - %kernel.root_dir%/../web/assets/rainbow-1.1.9/themes/github.css
            filters: [?yui_css, cssrewrite]

        javascripts_header:
            inputs:
                - %kernel.root_dir%/../web/assets/jquery/jquery-1.8.2.js
                - %kernel.root_dir%/../web/bundles/fosjsrouting/js/router.js
            filters: [?yui_js, cssrewrite]

        javascripts_footer:
            inputs:
                - %kernel.root_dir%/../web/assets/bootstrap-3.0.0/dist/js/bootstrap.min.js
                - %kernel.root_dir%/../web/assets/socialite/socialite.js

                # http://welldonethings.com/tags/manager/v3
                - %kernel.root_dir%/../web/assets/tagmanager-3.0.1/tagmanager.js

                # http://sugarjs.com/
                - %kernel.root_dir%/../web/assets/sugarjs-1.4.1/sugar.min.js

                #https://github.com/ccampbell/rainbow
                - %kernel.root_dir%/../web/assets/rainbow-1.1.9/js/rainbow.min.js
                - %kernel.root_dir%/../web/assets/rainbow-1.1.9/js/language/generic.js
                - %kernel.root_dir%/../web/assets/rainbow-1.1.9/js/language/php.js
                - %kernel.root_dir%/../web/assets/rainbow-1.1.9/js/language/html.js
                - %kernel.root_dir%/../web/assets/rainbow-1.1.9/js/language/javascript.js
                - %kernel.root_dir%/../web/assets/rainbow.linenumbers-master/js/rainbow.linenumbers.js

                - %kernel.root_dir%/../web/bundles/brickssite/js/*.js
                - %kernel.root_dir%/../web/bundles/brickssite/js/*/*.js
                - %kernel.root_dir%/../web/bundles/bricksmessage/js/*.js
            filters: [?yui_js, cssrewrite]